# K8s is extensible - we can add in our own custome objects.
# This specifies the set of objects we want K8s to look at
apiVersion: apps/v1

# The type of object we want to create
kind: Deployment

#Config options for the object we are about to create
metadata:
  # When the pod is created, give it a name of 'posts'
  name: posts

# The exact attributes we want to apply to the objects we
# about to create
spec:
  # Replicas is the number of pods that we want to create running
  # some particular image
  replicas: 1

  # In this case, we are telling the deployment that we
  # wanted to find all the different pods with a lable of app 'posts'
  # and those of the pods that it should be in incharge of
  selector:
    matchLabels:
      app: posts

  # The template is where we specify the exact configuration of a pod
  # that we want this deployment to create
  template:
    # This is the configuration that is going to be applied
    # to the pod that the deployment is going to make
    metadata:
      # We want the pod to have a lable of 'app: posts'
      labels:
        app: posts

    # The exact attributes we want to apply to the objects we
    # about to create
    spec:
      # Make a container with a name of 'posts'
      containers:
        - name: posts

          # The exact image we want to use
          image: gowtham1995/posts
          imagePullPolicy: Never
